/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/blacklist/common": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取通用黑名单列表 */
        get: operations["get_common_blocked_companies_blacklist_common_get"];
        put?: never;
        /** 批量添加通用的黑名单公司 */
        post: operations["add_blocked_companies_blacklist_common_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blacklist/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前角色的黑名单公司 */
        get: operations["get_current_role_blocked_companies_blacklist_current_get"];
        put?: never;
        /** 批量添加当前角色的黑名单公司 */
        post: operations["add_current_role_blocked_companies_blacklist_current_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blacklist/current/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除当前角色的黑名单公司 */
        delete: operations["delete_current_role_blocked_company_blacklist_current__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blacklist/common/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除通用的黑名单公司 */
        delete: operations["delete_blocked_company_blacklist_common__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blacklist/common/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重置通用黑名单列表 */
        post: operations["reset_common_blocked_companies_blacklist_common_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色列表 */
        get: operations["get_list_role__get"];
        put?: never;
        /** 创建角色 */
        post: operations["create_role_role__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新角色 */
        put: operations["update_role_role__role_id__put"];
        post?: never;
        /** 删除角色 */
        delete: operations["delete_role_role__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/{role_id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 设置默认角色 */
        put: operations["set_default_role_role__role_id__default_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前激活的角色 */
        get: operations["get_current_role_role_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有浏览记录 */
        get: operations["get_all_history__get"];
        put?: never;
        /** 添加浏览记录 */
        post: operations["add_history_history__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前角色的浏览记录 */
        get: operations["get_current_role_history_history_current_get"];
        put?: never;
        post?: never;
        /** 删除当前角色的浏览记录（清空当前角色所有记录） */
        delete: operations["delete_current_role_history_history_current_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除浏览记录 */
        delete: operations["delete_history_history__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前角色的岗位设置 */
        get: operations["get_current_position_position__get"];
        /** 更新当前角色的岗位设置 */
        put: operations["update_current_position_position__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockedCompany */
        BlockedCompany: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /**
         * BlockedCompanyCreate
         * @description 创建通用黑名单公司时使用的入参模型
         */
        BlockedCompanyCreate: {
            /** Name */
            name: string;
        };
        /** CurrentRoleBlockedCompany */
        CurrentRoleBlockedCompany: {
            /** Id */
            id?: number | null;
            /**
             * Role Id
             * @description 角色id
             */
            role_id: number;
            /** Name */
            name: string;
            /**
             * Reason
             * @description 理由
             */
            reason?: string | null;
        };
        /**
         * CurrentRoleBlockedCompanyCreate
         * @description 创建当前角色黑名单项时使用的入参模型（不暴露 role_id）
         */
        CurrentRoleBlockedCompanyCreate: {
            /** Name */
            name: string;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** History */
        History: {
            /**
             * Encryptid
             * @description 岗位的唯一id
             */
            encryptId: string;
            /**
             * Jobname
             * @description 岗位名称
             */
            jobName: string;
            /**
             * Url
             * @description 跳转url
             */
            url: string;
            /**
             * Companyname
             * @description 公司名称
             */
            companyName: string;
            /**
             * Salaryrange
             * @description 薪水范围
             */
            salaryRange: string;
            /**
             * Cityname
             * @description 城市名称
             */
            cityName: string;
            /** Id */
            id?: number | null;
            /**
             * Time
             * @description 时间戳
             */
            time?: number;
            /**
             * Role Id
             * @description 角色id
             */
            role_id: number;
        };
        /**
         * HistoryCreate
         * @description 创建浏览记录时使用的入参模型（不暴露 id、role_id、time）
         */
        HistoryCreate: {
            /**
             * Encryptid
             * @description 岗位的唯一id
             */
            encryptId: string;
            /**
             * Jobname
             * @description 岗位名称
             */
            jobName: string;
            /**
             * Url
             * @description 跳转url
             */
            url: string;
            /**
             * Companyname
             * @description 公司名称
             */
            companyName: string;
            /**
             * Salaryrange
             * @description 薪水范围
             */
            salaryRange: string;
            /**
             * Cityname
             * @description 城市名称
             */
            cityName: string;
        };
        /** Position */
        Position: {
            /**
             * White
             * @description 白名单
             */
            white?: string | null;
            /**
             * Black
             * @description 黑名单
             */
            black?: string | null;
            /**
             * Min Salary
             * @description 最低薪水
             */
            min_salary?: number | null;
            /**
             * Max Salary
             * @description 最高薪水
             */
            max_salary?: number | null;
            /**
             * Enabled
             * @description 是否启用
             * @default true
             */
            enabled: boolean;
            /**
             * City
             * @description 城市
             */
            city?: string | null;
            /**
             * Black Company Enabled
             * @description 黑名单公司过滤是否启用
             * @default true
             */
            black_company_enabled: boolean;
            /**
             * History Highlight Enabled
             * @description 浏览历史高亮是否启用
             * @default true
             */
            history_highlight_enabled: boolean;
            /** Id */
            id?: number | null;
            /**
             * Role Id
             * @description 角色id
             */
            role_id: number;
        };
        /**
         * PositionUpdate
         * @description 更新当前角色岗位设置时使用的入参模型（不暴露 id、role_id）
         */
        PositionUpdate: {
            /**
             * White
             * @description 白名单
             */
            white?: string | null;
            /**
             * Black
             * @description 黑名单
             */
            black?: string | null;
            /**
             * Min Salary
             * @description 最低薪水
             */
            min_salary?: number | null;
            /**
             * Max Salary
             * @description 最高薪水
             */
            max_salary?: number | null;
            /**
             * Enabled
             * @description 是否启用
             * @default true
             */
            enabled: boolean;
            /**
             * City
             * @description 城市
             */
            city?: string | null;
            /**
             * Black Company Enabled
             * @description 黑名单公司过滤是否启用
             * @default true
             */
            black_company_enabled: boolean;
            /**
             * History Highlight Enabled
             * @description 浏览历史高亮是否启用
             * @default true
             */
            history_highlight_enabled: boolean;
        };
        /** Role */
        Role: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_common_blocked_companies_blacklist_common_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedCompany"][];
                };
            };
        };
    };
    add_blocked_companies_blacklist_common_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockedCompanyCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_role_blocked_companies_blacklist_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentRoleBlockedCompany"][];
                };
            };
        };
    };
    add_current_role_blocked_companies_blacklist_current_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrentRoleBlockedCompanyCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_current_role_blocked_company_blacklist_current__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blocked_company_blacklist_common__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_common_blocked_companies_blacklist_common_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_list_role__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
        };
    };
    create_role_role__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_role__role_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_role__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_default_role_role__role_id__default_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_role_role_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"] | null;
                };
            };
        };
    };
    get_all_history__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"][];
                };
            };
        };
    };
    add_history_history__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_role_history_history_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"][];
                };
            };
        };
    };
    delete_current_role_history_history_current_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_history_history__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_position_position__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"] | null;
                };
            };
        };
    };
    update_current_position_position__put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
